version: '3'
services:
  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - 5555:5000
    depends_on:
      - mysql
  frontend:
    restart: always
    container_name: frontend
    build: ./frontend
    ports:
      - 8954:8954
    depends_on:
      - api
  mysql:
    restart: always
    image: mysql
    container_name: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8432:8080

volumes:
  mysql_data: